### ISSUE TITLE
远程主机强迫关闭现有连接

### ISSUE THREAD

**Issue by Sireneason** [MoonHugo/ComfyUI-BiRefNet-Hugo#2]
报错如下，检查了网络魔法正常使用
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
got prompt
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\comfyui\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by MoonHugo** [comment]
试下关了魔法再来试试看。

**Comment by Sireneason** [comment]
还是会有同样的问题

**Comment by MoonHugo** [comment]
> 还是会有同样的问题

到时我留意下，有答案再回复你。
