### ISSUE TITLE
节点无法加载，请帮忙看看是什么问题，模型已放在C盘

### ISSUE THREAD

**Issue by Andy2024mm** [MoonHugo/ComfyUI-BiRefNet-Hugo#9]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /ZhengPeng7/BiRefNet/resolve/main/config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-Hugo\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-Hugo\nodes.py", line 14, in <module>
    birefnet = AutoModelForImageSegmentation.from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 485, in from_pretrained
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1282, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 395, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /ZhengPeng7/BiRefNet/resolve/main/config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))"), '(Request ID: e4c86d38-de5f-4280-9369-4ad950318495)')

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-Hugo module for custom nodes: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /ZhengPeng7/BiRefNet/resolve/main/config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))"), '(Request ID: e4c86d38-de5f-4280-9369-4ad950318495)')

**Comment by MoonHugo** [comment]
你下载的模型存放路径和模型文件截图看看，看报错你应该是少下载了一个config.json文件。

**Comment by zmwv823** [comment]
> 你下载的模型存放路径和模型文件截图看看，看报错你应该是少下载了一个config.json文件。

不好说，使用repo_id(ZhengPeng7/BiRefNet)加载模型(缓存在.cache下)每次第一次执行需要连接huggingface，魔法稍微不稳定就过不了。
这就是为什么b站那么多人一直说报错，需要稳定的魔法。
直接给本地路径则不需要联网检查。

**Comment by Andy2024mm** [comment]
![image](https://github.com/user-attachments/assets/fab4fb67-7de1-4288-8b07-155a2ea1a2b4)
![image](https://github.com/user-attachments/assets/2180586a-675e-4e77-97a9-2135615f8dac)
这两个地方都放过，一样无法加载，config文件有下载啊

**Comment by zmwv823** [comment]
> ![image](https://private-user-images.githubusercontent.com/170286247/367319040-fab4fb67-7de1-4288-8b07-155a2ea1a2b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNDc2OTYsIm5iZiI6MTcyNjI0NzM5NiwicGF0aCI6Ii8xNzAyODYyNDcvMzY3MzE5MDQwLWZhYjRmYjY3LTdkZTEtNDI4OC04YjA3LTE1NWEyZWExYTJiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxNzA5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjAwYmQxMDAzZmYwMTA0ODBlYzM3NDkwNmFlYzFhYzY1NTU4MjljYTg2ZWFlYThmYjRiNWFhMWIxMTM4ODlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uznE8DM6VdBLqRgyrbjo6TS3e7FJErSZZAcrPluo1g8) ![image](https://private-user-images.githubusercontent.com/170286247/367319281-2180586a-675e-4e77-97a9-2135615f8dac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNDc2OTYsIm5iZiI6MTcyNjI0NzM5NiwicGF0aCI6Ii8xNzAyODYyNDcvMzY3MzE5MjgxLTIxODA1ODZhLTY3NWUtNGU3Ny05N2E5LTIxMzU2MTVmOGRhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxNzA5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDVkYmI3NWY2MmQyNWUzMmNhMWFjMTdkNDUyODYyZjE5OGJmNzVkNjg5OGRmNzRjOGUxZmYyYWJlNzYyYjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aUnuHpmrbozzwhtEUVOHnF2F6_Ere9zi6y9alXvUFvU) 这两个地方都放过，一样无法加载，config文件有下载啊

# 这才是repo_id模型的正确位置，blob编码(一串英文加数字的随机编号)。
![image](https://github.com/user-attachments/assets/aec9c9b8-9ad1-4246-967f-d1afe79557bb)
## 要是实在搞不定。。。。。。可以回退到9.4号的提交，把模型丢到下图里面位置， 刷新comfyui之后就可以从下拉列表选择。
![image](https://github.com/user-attachments/assets/33a26962-ac23-4b7b-bea3-6995f245c9da)

**Comment by Andy2024mm** [comment]
退回9月4号版本已解决，感谢！
